codeocean:
  url: http://localhost
omniauth:
  mocksaml:
    enable: false
  bird:
    enable: false
    certificate: ~
    private_key: ~
  nbp:
    enmeshed:
      app_store_link: 'https://apps.apple.com/de/app/mein-bildungsraum-wallet/id6467007352'
      play_store_link: 'https://play.google.com/store/apps/details?id=de.bildungsraum.wallet.beta'
      connector_url: 'https://enmeshed-connector.example.com:80'
      connector_api_key: myapikey
      display_name: CodeHarbor
      allow_certificate_request: false
    enable: false
    certificate: ~
    private_key: ~
oai_pmh:
  admin_mail: admin@example.org
nbp:
  push_connector:
    enable: true
    client_id: testing_client_id
    client_secret: testing_client_secret
    token_path: 'https://test.provider/token'
    api_host: 'https://test.api.host'
    source:
      organization: test_organization
      name: CodeHarbor
      slug: CoHaP2
open_ai:
  access_token: ~ # Add a valid API key from https://platform.openai.com/api-keys
  model: gpt-4o-mini
