codeocean:
  url: http://localhost
omniauth:
  mocksaml:
    enable: false
  bird:
    enable: false
    certificate: ~
    private_key: ~
  nbp:
    enmeshed:
      app_store_link: 'https://apps.apple.com/de/app/mein-bildungsraum-wallet/id6467007352'
      play_store_link: 'https://play.google.com/store/apps/details?id=de.bildungsraum.wallet.beta'
      connector_url: 'http://localhost:80'
      connector_api_key: myapikey
      display_name: CodeHarbor
    enable: false
    certificate: ~
    private_key: ~
oai_pmh:
  admin_mail: admin@example.org
open_ai:
  access_token: ~ # Add a valid API key from https://platform.openai.com/api-keys
  model: gpt-3.5-turbo
